package com.zjc.greendao.dao;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.database.Database;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.zjc.greendao.entity.Devprtline;
import com.zjc.greendao.entity.Desc;
import com.zjc.greendao.entity.History;
import com.zjc.greendao.entity.Netaddress;
import com.zjc.greendao.entity.Plan;
import com.zjc.greendao.entity.Tasks;
import com.zjc.greendao.entity.Tasktab;

import com.zjc.greendao.dao.DevprtlineDao;
import com.zjc.greendao.dao.DescDao;
import com.zjc.greendao.dao.HistoryDao;
import com.zjc.greendao.dao.NetaddressDao;
import com.zjc.greendao.dao.PlanDao;
import com.zjc.greendao.dao.TasksDao;
import com.zjc.greendao.dao.TasktabDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig devprtlineDaoConfig;
    private final DaoConfig descDaoConfig;
    private final DaoConfig historyDaoConfig;
    private final DaoConfig netaddressDaoConfig;
    private final DaoConfig planDaoConfig;
    private final DaoConfig tasksDaoConfig;
    private final DaoConfig tasktabDaoConfig;

    private final DevprtlineDao devprtlineDao;
    private final DescDao descDao;
    private final HistoryDao historyDao;
    private final NetaddressDao netaddressDao;
    private final PlanDao planDao;
    private final TasksDao tasksDao;
    private final TasktabDao tasktabDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        devprtlineDaoConfig = daoConfigMap.get(DevprtlineDao.class).clone();
        devprtlineDaoConfig.initIdentityScope(type);

        descDaoConfig = daoConfigMap.get(DescDao.class).clone();
        descDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        netaddressDaoConfig = daoConfigMap.get(NetaddressDao.class).clone();
        netaddressDaoConfig.initIdentityScope(type);

        planDaoConfig = daoConfigMap.get(PlanDao.class).clone();
        planDaoConfig.initIdentityScope(type);

        tasksDaoConfig = daoConfigMap.get(TasksDao.class).clone();
        tasksDaoConfig.initIdentityScope(type);

        tasktabDaoConfig = daoConfigMap.get(TasktabDao.class).clone();
        tasktabDaoConfig.initIdentityScope(type);

        devprtlineDao = new DevprtlineDao(devprtlineDaoConfig, this);
        descDao = new DescDao(descDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);
        netaddressDao = new NetaddressDao(netaddressDaoConfig, this);
        planDao = new PlanDao(planDaoConfig, this);
        tasksDao = new TasksDao(tasksDaoConfig, this);
        tasktabDao = new TasktabDao(tasktabDaoConfig, this);

        registerDao(Devprtline.class, devprtlineDao);
        registerDao(Desc.class, descDao);
        registerDao(History.class, historyDao);
        registerDao(Netaddress.class, netaddressDao);
        registerDao(Plan.class, planDao);
        registerDao(Tasks.class, tasksDao);
        registerDao(Tasktab.class, tasktabDao);
    }
    
    public void clear() {
        devprtlineDaoConfig.getIdentityScope().clear();
        descDaoConfig.getIdentityScope().clear();
        historyDaoConfig.getIdentityScope().clear();
        netaddressDaoConfig.getIdentityScope().clear();
        planDaoConfig.getIdentityScope().clear();
        tasksDaoConfig.getIdentityScope().clear();
        tasktabDaoConfig.getIdentityScope().clear();
    }

    public DevprtlineDao getDevprtlineDao() {
        return devprtlineDao;
    }

    public DescDao getDescDao() {
        return descDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

    public NetaddressDao getNetaddressDao() {
        return netaddressDao;
    }

    public PlanDao getPlanDao() {
        return planDao;
    }

    public TasksDao getTasksDao() {
        return tasksDao;
    }

    public TasktabDao getTasktabDao() {
        return tasktabDao;
    }

}
