package com.zjc.greendao.dao;

import android.database.Cursor;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.database.Database;
import de.greenrobot.dao.database.DatabaseStatement;

import com.zjc.greendao.entity.Devprtline;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DEVPRTLINE".
*/
public class DevprtlineDao extends AbstractDao<Devprtline, Void> {

    public static final String TABLENAME = "DEVPRTLINE";

    /**
     * Properties of entity Devprtline.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Phynum = new Property(0, String.class, "phynum", false, "PHYNUM");
        public final static Property Rfid = new Property(1, String.class, "rfid", false, "RFID");
        public final static Property Assetnum = new Property(2, String.class, "assetnum", false, "ASSETNUM");
    };


    public DevprtlineDao(DaoConfig config) {
        super(config);
    }
    
    public DevprtlineDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DEVPRTLINE\" (" + //
                "\"PHYNUM\" TEXT," + // 0: phynum
                "\"RFID\" TEXT," + // 1: rfid
                "\"ASSETNUM\" TEXT);"); // 2: assetnum
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DEVPRTLINE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(DatabaseStatement stmt, Devprtline entity) {
        stmt.clearBindings();
 
        String phynum = entity.getPhynum();
        if (phynum != null) {
            stmt.bindString(1, phynum);
        }
 
        String rfid = entity.getRfid();
        if (rfid != null) {
            stmt.bindString(2, rfid);
        }
 
        String assetnum = entity.getAssetnum();
        if (assetnum != null) {
            stmt.bindString(3, assetnum);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public Devprtline readEntity(Cursor cursor, int offset) {
        Devprtline entity = new Devprtline( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // phynum
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // rfid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // assetnum
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Devprtline entity, int offset) {
        entity.setPhynum(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setRfid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAssetnum(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(Devprtline entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(Devprtline entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
