package com.zjc.greendao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DESC".
 */
public class Desc {

    private String assetnum;
    private String regular;
    private String executeby;
    private String type;

    public Desc() {
    }

    public Desc(String assetnum, String regular, String executeby, String type) {
        this.assetnum = assetnum;
        this.regular = regular;
        this.executeby = executeby;
        this.type = type;
    }

    public String getAssetnum() {
        return assetnum;
    }

    public void setAssetnum(String assetnum) {
        this.assetnum = assetnum;
    }

    public String getRegular() {
        return regular;
    }

    public void setRegular(String regular) {
        this.regular = regular;
    }

    public String getExecuteby() {
        return executeby;
    }

    public void setExecuteby(String executeby) {
        this.executeby = executeby;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
