package com.zjc.greendao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DEVPRTLINE".
 */
public class Devprtline {

    private String phynum;
    private String rfid;
    private String assetnum;

    public Devprtline() {
    }

    public Devprtline(String phynum, String rfid, String assetnum) {
        this.phynum = phynum;
        this.rfid = rfid;
        this.assetnum = assetnum;
    }

    public String getPhynum() {
        return phynum;
    }

    public void setPhynum(String phynum) {
        this.phynum = phynum;
    }

    public String getRfid() {
        return rfid;
    }

    public void setRfid(String rfid) {
        this.rfid = rfid;
    }

    public String getAssetnum() {
        return assetnum;
    }

    public void setAssetnum(String assetnum) {
        this.assetnum = assetnum;
    }

}
