package com.zjc.greendao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NETADDRESS".
 */
public class Netaddress {

    private String name;
    private String netaddress;

    public Netaddress() {
    }

    public Netaddress(String name, String netaddress) {
        this.name = name;
        this.netaddress = netaddress;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNetaddress() {
        return netaddress;
    }

    public void setNetaddress(String netaddress) {
        this.netaddress = netaddress;
    }

}
