package com.zjc.greendao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "TASKS".
 */
public class Tasks {
//    @SerializedName("PHYNUM")
    private String phynum;
//    @SerializedName("RFID")
    private String rfid;
//    @SerializedName("ASSETNUM")
    private String assetnum;
//    @SerializedName("DESCRIPTION")
    private String description;
//    @SerializedName("TYPE")
    private String type;

    public Tasks() {
    }

    public Tasks(String phynum, String rfid, String assetnum, String description, String type) {
        this.phynum = phynum;
        this.rfid = rfid;
        this.assetnum = assetnum;
        this.description = description;
        this.type = type;
    }

    public String getPhynum() {
        return phynum;
    }

    public void setPhynum(String phynum) {
        this.phynum = phynum;
    }

    public String getRfid() {
        return rfid;
    }

    public void setRfid(String rfid) {
        this.rfid = rfid;
    }

    public String getAssetnum() {
        return assetnum;
    }

    public void setAssetnum(String assetnum) {
        this.assetnum = assetnum;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public String toString() {
        return "phynum='" + phynum + '\'' +
                ", rfid='" + rfid + '\'' +
                ", assetnum='" + assetnum + '\'' +
                ", description='" + description + '\'' +
                ", type='" + type + '\'' +
                '}';
    }
}
